language: go
go_import_path: github.com/ShyftNetwork/go-empyrean

env:
  matrix:
    - TRAVIS_GO_VERSION = 1.10.x
    - TRAVIS_GO_VERSION = 1.11.x

os: linux
dist: trusty
sudo: required
cache:
  timeout: 259200 # 72 hours
  directories:
  - $TRAVIS_BUILD_DIR/.git/modules
install:
- go get -t ./...
script:
- make geth && go test ./...
