language: go
go_import_path: github.com/ShyftNetwork/go-empyrean



matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    go:
    - 1.10.x
    - 1.11.x
    cache:
      timeout: 259200 # 72 hours
      directories:
      - $TRAVIS_BUILD_DIR/.git/modules
    install:
    - go get -t ./...
    script:
    - make geth && go test ./...
#  - os: osx
#    sudo: required
#    cache:
#      timeout: 259200 # 72 hours
#      directories:
#      - $TRAVIS_BUILD_DIR/.git/modules
#    install:
#    - brew install postgresql@9.6
#    - brew services start postgresql
#    - go get -t ./...
#    before_script:
#    - createuser -s postgres
#    - psql -c 'create database shyftdbtest;' -U postgres
#    - psql -c 'create database shyftdbtest_2;' -U postgres
#    script:
#    - echo "Dummy run" #make geth && go test ./...



