language: go
go_import_path: github.com/ShyftNetwork/go-empyrean
go:
- 1.10.x
- 1.11.x

matrix:
  include:
  # Linux
  - os: linux
    dist: trusty
    sudo: required
    env:
    - ENV=linux
    cache:
      timeout: 259200 # 72 hours
      directories:
      - $TRAVIS_BUILD_DIR/.git/modules
    install:
    - go get -t ./...
    script:
    - make geth && go test ./...

  # OSX
  - os: osx
    sudo: required
    env:
    - ENV=OSX
    cache:
      timeout: 259200 # 72 hours
      directories:
      - $TRAVIS_BUILD_DIR/.git/modules
    install:
    - brew install postgresql@9.6
    - brew services start postgresql
    - go get -t ./...
    before_script:
    - createuser -s postgres
    script:
    - make geth && go test ./...