language: go

go:
  - "1.10.4"
  - "1.10.3"

services:
  - postgresql

addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6
    - postgresql-client-9.6

install:
  - go get -t ./...

before_install:
  - sudo apt-get update
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start 9.6

before_script:
  - psql -c 'create database shyftdbtest;' -U postgres
  - psql -c 'create database shyftdbtest_2;' -U postgres

script:
  - make geth
  - go test ./... -parallel 2