language: go

go:
  - "1.10.4"
  - "1.10.3"
  - "1.10.1"

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5432

before_install:
  - sudo apt-get update
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start

before_script:
  - psql -c 'create database shyftdbtest;' -U postgres
  - psql -c 'create database shyftdbtest_2;' -U postgres

script:
  - make geth
  - go test ./... -parallel 2 -v