version: '3'
services:
  shyftgeth:
    build:
      context: $PWD 
      dockerfile: docker/production/shyftGeth/Dockerfile
    ports:
      - "8545:8545"
      - "8546:8546"
      - "31333:31333"
      - "31333:31333/udp"
      - "8081:8081"
    volumes:
      - ./shyftData:/go/src/github.com/ShyftEthereum/go-empyrean/shyftData
    working_dir: /go/src/github.com/ShyftEthereum/go-empyrean
    networks:
      - shyftnet
    command: >
      sh -c 'cd /go/src/github.com/ShyftEthereum/go-empyrean/ &&
            ./shyft-cli/initShyftGeth.sh &&
            ./shyft-cli/startShyftGeth.sh'
networks:
  shyftnet:
    driver: bridge
  

